### ISSUE TITLE
Mismatching guard regarding available fields and linux kernel version

### ISSUE THREAD

**Issue by Raphalex46** [jmuehlig/perf-cpp#7]
Hi, I'm not sure if I'm missing something, but I'm encountering the following issue:

When building, some define is missing:
```
error: ‘PERF_MEM_LVLNUM_UNC’ was not declared in this scope; did you mean ‘PERF_MEM_LVLNUM_NA’?
  503 |   data_access_source.is_uncachable_memory(memory_level_code == PERF_MEM_LVLNUM_UNC);
      |                                                                ^~~~~~~~~~~~~~~~~~~
      |                                                                PERF_MEM_LVLNUM_NA
```

When searching I found that the first path of this pre-processor guard is taken in this [file](https://github.com/jmuehlig/perf-cpp/blob/dev/src/sample_decoder.cpp):
```cpp
#ifndef PERFCPP_NO_MEM_LVLNUM /// lvl_num field is supported since Linux 6.1
  data_access_source.is_l1_hit(memory_level_code == PERF_MEM_LVLNUM_L1);
  data_access_source.is_l2_hit(memory_level_code == PERF_MEM_LVLNUM_L2);
  data_access_source.is_l3_hit(memory_level_code == PERF_MEM_LVLNUM_L3);
  data_access_source.is_l4_hit(memory_level_code == PERF_MEM_LVLNUM_L4);
  data_access_source.is_memory_hit(memory_level_code == PERF_MEM_LVLNUM_RAM);
  data_access_source.is_mhb_hit(memory_level_code == PERF_MEM_LVLNUM_LFB);
  data_access_source.is_uncachable_memory(memory_level_code == PERF_MEM_LVLNUM_UNC);
#else /// Use lvl before Linux 6.1
  data_access_source.is_l1_hit((memory_level_code & PERF_MEM_LVL_L1) && (memory_level_code & PERF_MEM_LVL_HIT));
  data_access_source.is_l2_hit((memory_level_code & PERF_MEM_LVL_L2) && (memory_level_code & PERF_MEM_LVL_HIT));
  data_access_source.is_l3_hit((memory_level_code & PERF_MEM_LVL_L3) && (memory_level_code & PERF_MEM_LVL_HIT));
  data_access_source.is_memory_hit((memory_level_code & PERF_MEM_LVL_LOC_RAM) ||
                                   (memory_level_code & PERF_MEM_LVL_REM_RAM1) ||
                                   (memory_level_code & PERF_MEM_LVL_REM_RAM2));
  data_access_source.is_mhb_hit((memory_level_code & PERF_MEM_LVL_LFB) && (memory_level_code & PERF_MEM_LVL_HIT));
  data_access_source.is_uncachable_memory(memory_level_code & PERF_MEM_LVL_UNC);
#endif
```
But when looking at where this guard is set, I found the following code [here](https://github.com/jmuehlig/perf-cpp/blob/dev/include/perfcpp/feature.h):
```cpp
#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 14, 0)
#define PERFCPP_NO_MEM_LVLNUM
#define PERFCPP_NO_MEM_LVLNUM_PMEM
#define PERFCPP_NO_MEM_REMOTE
#define PERFCPP_NO_MEM_SNOOPX
#endif
```

Here's some output for my kernel and perf versions:
```
$ uname -r
5.15.0-142-generic
$ perf --version
perf version 5.15.180
```

So, according to the comment, since my kernel is < 6.1, `PERFCPP_NO_MEM_LVLNUM` should be defined, but according to the `features.h` file it shouldn't, I believe that's what causing the problem here. Clearly my 5.15 kernel and perf don't have this feature.

Is this normal? I can probably work around this by forcing the define but I wonder if there is something I misunderstood.

**Comment by jmuehlig** [comment]
Hi, you're right, that is indeed a bug in the library. Could you try if the v0.12-dev branch already fixes this?

**Comment by Raphalex46** [comment]
> Hi, you're right, that is indeed a bug in the library. Could you try if the v0.12-dev branch already fixes this?

Yes, I can try. I don't have much time right now, but if I can't do it today, I'll do it asap and keep you updated :)

**Comment by Raphalex46** [comment]
I just tried it and it seems to be fixed on the `0.12-dev` branch.

I still have the following error through, but I didn't look into it:
```
error: ‘PERF_MEM_SNOOPX_PEER’ was not declared in this scope; did you mean ‘PERF_MEM_SNOOPX_FWD’?
  538 |       snoop.is_transfer_from_peer(snoopx_code & PERF_MEM_SNOOPX_PEER);
      |                                                 ^~~~~~~~~~~~~~~~~~~~
      |                                                 PERF_MEM_SNOOPX_FWD
```

**Comment by jmuehlig** [comment]
Thanks for pointing that out. I believe I've found and fixed the bug at branch `v0.12-dev` (the field was being used without checks); however, I wasn't able to test it on every kernel version. Please try again and let me know whether the latest update resolves the issue.

**Comment by Raphalex46** [comment]
Just checked, it works on my 5.15 kernel version :)

**Comment by jmuehlig** [comment]
Fixed in `v0.12.4`. Thanks for your assistance.
